version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - easyschooldb
  easyschooldb:
    image: "mysql:8.1"
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: myschooldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_HOST: easyschooldb






